"""empty message

Revision ID: f52bf951262a
Revises: 73e4c05f0b78
Create Date: 2020-06-30 23:22:04.217033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f52bf951262a'
down_revision = '73e4c05f0b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'f_id')
    op.drop_column('permissions', 'created_by')
    op.drop_column('permissions', 'updated_by')
    op.drop_column('permissions', 'created_at')
    op.drop_column('role_permissions', 'created_by')
    op.drop_column('role_permissions', 'updated_at')
    op.drop_column('role_permissions', 'f_id')
    op.drop_column('role_permissions', 'updated_by')
    op.drop_column('role_permissions', 'created_at')
    op.drop_column('roles', 'created_by')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'f_id')
    op.drop_column('roles', 'updated_by')
    op.drop_column('roles', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('f_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('role_permissions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('role_permissions', sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('role_permissions', sa.Column('f_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('role_permissions', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('role_permissions', sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('permissions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('permissions', sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('permissions', sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('permissions', sa.Column('f_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('permissions', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
